# Generated by Django 5.0.7 on 2024-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lga',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
