# Generated by Django 5.0.7 on 2024-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_lga_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Nigeria', max_length=7),
        ),
    ]
