# Generated by Django 5.0.7 on 2024-07-18 23:20

import django.db.models.deletion
import main.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_profile_location_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('Mercedes Benz', 'Mercedes Benz'), ('Audi', 'Audi'), ('Subanu', 'Subanu'), ('Tesla', 'Tesla'), ('Jagular', 'Jagular'), ('Land Rover', 'Land Rover'), ('Bentley', 'Bentley'), ('Bugatti', 'Bugatti'), ('Ferrari', 'Ferrari'), ('Lamborgini', 'Lamborgini'), ('Honda', 'Honda'), ('Kia', 'Kia'), ('Toyota', 'Toyota'), ('Chevrolet', 'Chevrolet'), ('Porsche', 'Porsche'), ('Camry', 'Camry'), ('Corolla', 'Corolla'), ('Nissan', 'Nissan')], default=None, max_length=30)),
                ('model', models.CharField(max_length=64)),
                ('vin', models.CharField(max_length=17)),
                ('mileage', models.IntegerField(default=0)),
                ('color', models.CharField(default='White', max_length=24)),
                ('description', models.TextField()),
                ('engine', models.CharField(max_length=64)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default=None, max_length=24)),
                ('Image', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
